# Generated by Django 4.0 on 2021-12-22 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_id_alter_usersettings_id_voting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.CharField(default='define me!', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votefact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voting',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voting',
            name='type',
            field=models.IntegerField(default=2),
        ),
    ]
