# Generated by Django 4.0 on 2022-01-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_complaint_description_complaint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='type',
            field=models.IntegerField(default=3),
        ),
    ]
