# Generated by Django 4.0 on 2022-01-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_voting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votefact',
            name='variant',
        ),
        migrations.CreateModel(
            name='VoteFactVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.votefact')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.votevariant')),
            ],
        ),
    ]
