# Generated by Django 4.0 on 2022-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_votefact_variant_votefactvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.IntegerField(default=0),
        ),
    ]
